**kalin yazamak icin basina ve sonuna iki tane ** isareti koymalisin**

In [2]:
#shift + enter

In [6]:
# b tusu ile yeni hucre ekleyebiliriz, 
# dd ile hucre silme yapabiliriz
# x ile hucre kesme
# v tusu ile hucre yapistirma 
# c tusu ile hucre kopyalama
# shifte basili tutup birden fazla hucre secip silebilirsin


# ANA BASLIK yapabilmek icin once markdown u secip # isareti yaparsin

## alt baslik yapabilmek icin once markdown u secip ## isareti yaparsin


* markdown yaptiktan sonra basina bir yildiz isareti koyunca maddeler halinde oluyor

* **deniz**

In [1]:
# np.array()
# import numpy as np
# np.array()   /*/
# np.array([1,2,3,4], dtype = 'float32') /*/
# np.zeros(10, dtype = int) /*/
# np.ones((3,5), dtype = int) /*/
# np.arange(0,31,3)
# np.linspace(0,90,10)
# np.random.normal(10,4,(3,4))
# np.random.randint(3,12,(3,3))
# np.full((3,5),4)
# a = np.random.randint(10,size=10)
# a.ndim
# a.shape 
# a.size
# a.dtype
# np.arange(1,10).reshape((3,3)) 
# np.concatenate([x,y])
# np.concatenate([b,b], axis = 1)
# np.split(a,[2,5])
# np.vsplit(b,[2])
# np.hsplit(b,[1])
# np.sort(k)
# np.sort(k, axis = 1)
# alt_l = l[0:2,1:2].copy()
# np.log2(m)
# x = np.linalg.solve(a,b) a x lerin katsayilari, b de sabit sayilar




In [7]:
a = [1,2,3,4]
b = [2,3,4,5]
a
b

[2, 3, 4, 5]

In [4]:
import numpy as np

In [13]:
a = np.array(a)  #array olusturmak icin bu sekilde...

In [10]:
b = np.array(b)

In [11]:
a*b

array([ 2,  6, 12, 20])

In [12]:
#numpy her bir liste icin sadece bir tane veri tutarken diger uygulamalarda her bir eleman icin bir veri tutulur

In [15]:
np.array([1,2,3,4], dtype = 'float32') 
#boylece listenin veri tipini kendimiz de secebiliyoruz

array([1., 2., 3., 4.], dtype=float32)

In [25]:
np.zeros(10, dtype = int)
#10 tane 0'i int tipinde yaz demis olduk

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.ones((3,5), dtype = int)
#3 satir 5 sutun olacak sekilde int olan 1 leri dizi olustur


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
np.arange(0,31,3)
# 0 ile 31 arasindaki sayilari 3 er 3 er arttirarak dizi olustur

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [28]:
np.linspace(0,90,10)
# 0 ile 90 arasinda 10 tane deger olustur dedigimizde homojen bir dizi uretir

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [29]:
np.random.normal(10,4,(3,4))
#normal dagilim olsun,ortalamasi 10, standart sapmasi 4, (3,4) satir ve sutun sayili bir array olusturmak icin

array([[ 3.98999606, 10.45875001, 10.42875939,  6.91188008],
       [ 8.26228747, 11.272245  ,  7.77862195,  8.21187788],
       [11.58058149,  7.9301959 ,  6.02585708,  8.71613158]])

In [33]:
#dagilimi onemsemiyorum,3 ile 12 arasinda 3e 3 bir liste olustur dersem
np.random.randint(3,12,(3,3))

array([[ 3, 11,  6],
       [10, 10, 11],
       [ 8,  9,  3]])

In [34]:
np.full((3,5),4)
#3 e 5 olacak sekilde 4 degeri ile fulle diziyi

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [39]:
a = np.random.randint(10,size=10)
#eger baslangic degeri vermezsen default 0 dan baslar

In [41]:
a.ndim #boyut sayisi

1

In [43]:
a.shape #bir boyutlu ve icerisinde 10 tane eleman var diyor

(10,)

In [45]:
a.size #toplam eleman sayisini verir

10

In [47]:
a.dtype #elemanlarin tipini verir

dtype('int64')

In [50]:
np.arange(1,10).reshape((3,3)) 
#reshape ile tek boyutlu array 3 e 3 e donusturulebiliyor

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
x= np.array([1,2,3])
y = np.array([4,5,6])

In [52]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [53]:
#peki yukaridaki birlestirmeyi iki boyutlu yaparsak;

In [56]:
b = np.array([[1,2,3],
             [4,5,6]])

In [58]:
np.concatenate([b,b])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
#peki satir bazinda degil de sutun bazinda birlestirmek istersek;

In [62]:
np.concatenate([b,b], axis = 1)
#0= satir
#1=sutun

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [63]:
a

array([0, 0, 9, 0, 4, 4, 3, 8, 4, 7])

In [67]:
np.split(a,[2,5])
#2 ve 5 indexlerini vererek 3 parcaya bolduk bu arrayi

[array([0, 0]), array([9, 0, 4]), array([4, 3, 8, 4, 7])]

In [74]:
a,t,c = np.split(a,[2,5])

In [75]:
a

array([0, 0])

In [77]:
t

array([], dtype=int64)

In [71]:
c

array([4, 3, 8, 4, 7])

In [81]:
b = np.array([[1,2,3],
             [4,5,6]])

In [83]:
np.vsplit(b,[2])
#vertical split

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([], shape=(0, 3), dtype=int64)]

In [85]:
np.hsplit(b,[1])
#horizontal split

[array([[1],
        [4]]),
 array([[2, 3],
        [5, 6]])]

In [98]:
k = [[1,10,2],[3,9,6]]

In [99]:
np.sort(k)

array([[ 1,  2, 10],
       [ 3,  6,  9]])

In [100]:
np.sort(k, axis = 1)

array([[ 1,  2, 10],
       [ 3,  6,  9]])

In [101]:
np.sort(k, axis = 0)

array([[ 1,  9,  2],
       [ 3, 10,  6]])

In [102]:
k

[[1, 10, 2], [3, 9, 6]]

In [5]:
l = np.random.randint(1,5,[2,2])

In [6]:
l

array([[3, 1],
       [3, 4]])

In [7]:
l[0]

array([3, 1])

In [8]:
l[1]

array([3, 4])

In [9]:
l[-1]

array([3, 4])

In [12]:
l = np.random.randint(10, size = [2,4])

In [13]:
l

array([[4, 3, 6, 4],
       [9, 9, 1, 0]])

In [14]:
l[1,2]

1

In [16]:
l[0:2,1:2]

array([[3],
       [9]])

In [17]:
l[:,2]

array([6, 1])

In [18]:
# alt kumeyi degistirince ana kume de degisir, bunu onlemek icin copy yapmalisin

In [19]:
alt_l = l[0:2,1:2].copy()

In [20]:
alt_l

array([[3],
       [9]])

In [24]:
[l[1,1], l[0,3]]

[9, 4]

In [25]:
m = np.arange(9).reshape(3,3)

In [26]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
satir = np.array([0,1])
sutun = np.array([1,2])
#biz aslinda bir sonraki islem icin index vermis olduk bu ifadelerle

In [29]:
m[satir,sutun]
# 0.satir 1. sutun, ve 1.satir 2.sutun daki elemanlari ceker ve liste yapar

array([1, 5])

In [31]:
m<4

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [33]:
m[m<4]
#kosulllu eleman islemleri

array([0, 1, 2, 3])

In [34]:
m[m%2==0]

array([0, 2, 4, 6, 8])

In [35]:
m-1

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [39]:
m+2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [41]:
m = m +2

In [46]:
np.log2(m)

array([[1.        , 1.5849625 , 2.        ],
       [2.32192809, 2.5849625 , 2.80735492],
       [3.        , 3.169925  , 3.32192809]])

5 * x0 + x1 = 12

x0 + 3 * x1 = 10

bu iki bilinmeyenli denklemi nupy kullanarak cozecegiz

In [50]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [51]:
x = np.linalg.solve(a,b)

In [52]:
x


array([1.85714286, 2.71428571])

In [53]:
a =np.array([[4, 7, 4, 5, 9],

            [2, 5, 0, 7, 7],

            [1, 9, 0, 8, 2]])

In [54]:
a

array([[4, 7, 4, 5, 9],
       [2, 5, 0, 7, 7],
       [1, 9, 0, 8, 2]])

In [55]:
a[:2,:3]

array([[4, 7, 4],
       [2, 5, 0]])

In [56]:
v = np.array([[0, 1, 2],

             [3, 4, 5],

             [6, 7, 8]]) 

In [57]:
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
v[1, [1,2]]

array([4, 5])